spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        jdbc:
          lob:
            non_contextual_creation: true