server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todo-app?useSSL=false&serverTimezone=UTC
    username: hbstudent
    password: hbstudent
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true