spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: dariusdatasolutions@gmail.com
    password: DariusDataSolutions000
    protocol: smtp
    properties:
      mail:
        smtp:
          starttls:
            enable: true
    default-encoding: UTF-8